version: '3.9'
services:
  graph-node:
    image: intothefathom/graph-node:latest
    ports:
      - '8000:8000'
      - '8001:8001'
      - '127.0.0.1:8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    environment:
      postgres_host: graph-node-2-db-do-user-12810364-0.b.db.ondigitalocean.com
      postgres_user: doadmin
      postgres_port: 25060
      postgres_db: defaultdb
      ipfs: '5001:5001'
      ethereum: 'mainnet:no_eip1898,archive:https://arpc.apothem.network/'
      GRAPH_LOG: info
      EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: synced
    entrypoint: "/bin/sh -c 'postgres_pass=`cat /run/secrets/postgres_password` start'" 
    secrets:
      - postgres_password
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    # volumes:
    #   - ./data/ipfs:/data/ipfs
secrets:
  postgres_password:
    external: true