name: Graph Build and Deployment

# on:
#   pull_request:
#     types:
#     - closed
#     branches:
#     - dev

on:
  push:
    branches:
    - github-action-do

jobs:

#Build the image and push to dockerhub
#The job condition says “Run this for everything EXCEPT non-merged closed PRs”.
  # build:
  #   # if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))

  #   name: Build & Push To Dockerhub

  #   runs-on: ubuntu-latest
  #   timeout-minutes: 70

  #   steps:

  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Build image
  #     run: docker build --target graph-node -t intothefathom/graph-node -f docker/Dockerfile .

  #   - name: View image details
  #     run: docker images

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #     with:
  #       username: ${{ secrets.DOCKER_USER }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   # - name: Add docker tag 
  #   #   run: docker tag graph-node intothefathom/graph-node:latest

  #   - name: Push Graph Node Image to DockerHub
  #     run: docker push intothefathom/graph-node:latest

  deploy:
    # needs: build
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:



    - name: Checkout code
      uses: actions/checkout@v3

    - name: Executing remote command 
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
           touch test.txt

          #  rm docker-compose.yml
          #  curl https://raw.githubusercontent.com/Into-the-Fathom/graph-node/dev/docker/docker-compose.yml >> docker-compose.yml && docker stack deploy -c docker-compose.yml graph-node --resolve-image always
           